version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017/
      - DBNAME=videos
      - VIDEO_STORAGE_HOST=http://video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no"

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=steven
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_DEFAULT_BUCKETS=videos
    restart: "no"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/bitnami/minio/data

  video-storage:
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - USER=steven
      - PASSWORD=changeme
      - BUCKET=video-streaming
    restart: "no"

  db:
    image: mongo:7
    container_name: db
    ports:
      - "4000:27017"
    restart: always
    depends_on:
      - minio
