version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=http://video-storage
      - VIDEO_STORAGE_PORT=80
    container_name: video-streaming
    ports:
      - "4000:80"
    restart: "no"
    depends_on:
      - minio

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=steven
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_DEFAULT_BUCKETS=videos
    restart: "no"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/bitnami/minio/data

  video-storage:
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    environment:
      - BUCKET=videos
      - MINIO_ROOT_USER=steven
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_STORAGE_HOST=http://minio
      - MINIO_STORAGE_PORT=9000
      - PORT=80
    ports:
      - "4001:80"
    restart: "no"
