version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_DEFAULT_BUCKETS=test-bucket
    restart: "no"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/bitnami/minio/data

  video-storage:
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=changeme
      - MINIO_ENDPOINT=minio
    restart: "no"
